apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: usofga01q-nodejs
  janus-idp.io/tekton: usofga01q-nodejs
  backstage.io/kubernetes-id: usofga01q-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: usofga01q-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
